[project]
name = "kokoro-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "fastapi>=0.141.1",
    "kokoro>=0.9.4",
    "numpy>=2.5.1",
    "soundfile>=0.14.0",
    "uvicorn>=0.52.1",
]

[project.scripts]
kokoro = "kokoro:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
